---
- hosts: localhost
  vars:
    # Run all tests by default
    # Can be overridden by ansible-playbook -e "fmf_filter='tags: ...'"
    fmf_filter: "tags: .*"
  tags:
    - classic
  roles:
    - role: standard-test-beakerlib
